partial update

diff --git a/dhelper b/dhelper
--- a/dhelper
+++ b/dhelper
@@ -9,25 +9,25 @@ debug_mode=0
 dockerfile="Dockerfile.default"
 JOBS=$(nproc --all)
 container_id=
-created_container=
+force=0
 attach=0
 persist=0
 auto_select=0
 image_tag="dev"
+extra_args=()
 
 # ================================================================================================
 #                                            GLOBALS
 DEPENDENCIES=("tput" "cam" "lsusb" "docker" "buildg")
 
-force=n
-
+created_container=
 selected_item_index=
 
 # ================================================================================================
 #                                             TASKS
 # (1: message to print)
 function debug () {
-    [[ ${debug_mode} -eq 0 ]] && echo $1
+    [[ ${debug_mode} -eq 1 ]] && echo $1
 }
 
 function init () {
@@ -42,8 +42,10 @@ function validate_dependencies () {
     return
 }
 
+
+# sets variables `cam_output`, `ids`, `lsusb_output`, `bus_ids`, `bus_addrs`, `usb_list` for use elsewhere
 function usb_init () {
-    # Store video devices
+    # Store video devices using libcamera
     cam_output=$(cam -l 2>/dev/null)
 
     # Find device entries like "UVC Camera (046d:0825) (usb-0000:00:14.0-3)"
@@ -53,6 +55,7 @@ function usb_init () {
     # highlight the device IDs in pink
     cam_output=$(echo "${cam_output}" | sed -E "s@(${ids})@\o033[45;30m&\o033[0m@g")
 
+    # Store usb devices using usbutils
     lsusb_output=$(lsusb)
 
     bus_ids=$(echo "${lsusb_output}" | sed -En "s/Bus ([0-9]{3}) Device ([0-9]{3}): ID (${ids}).*/\1/p" | awk '{ printf "%d,", $1 }' | head -c -1)
@@ -69,14 +72,21 @@ function usb_init () {
         # Find the ID from the match
         local addition=(${id_list[$i]},${addr_list[$i]})
         usb_list+=(${addition})
+    done
+}
 
+function validate_usb_devices () {
+    for ((i=0; i<${#id_list[@]}; i++)); do
         local id=$(printf "%0.3i" ${id_list[$i]})
         local addr=$(printf "%0.3i" ${addr_list[$i]})
         local device="/dev/bus/usb/${id}/${addr}"
 
+        # TODO: Check why this works on some systems and not others
         # Check permissions for the device
-        if [[ ! -w "${device}" ]]; then
+        if [[ ! -w "${device}" && ${force} -eq 0 ]]; then
             error ${BASH_SOURCE[0]} ${LINENO} "Device '${device}' is not writable by the current user, please chown the device" 120
+        elif [[ ! -w "${device}" && ${force} -eq 1 ]]; then
+            echo "Device '${device}' is not writable by the current user, please chown the device. Forcing..."
         fi
     done
 }
@@ -118,16 +128,16 @@ function run_container () {
     
     local device_args=""
     for dev in $(ls /dev/{video,media}* 2>/dev/null); do
-        device_args="$device_args --device=$dev"
+        device_args="${device_args} --device=${dev}"
     done
 
-    if [[ -z "$device_args" && "$force" == "n" ]]; then
+    if [[ -z "${device_args}" && ${force} -eq 0 ]]; then
         echo "No video devices found. Run with -f to force run"
         exit 3
     fi
 
     __rm="--rm"
-    [[ $persist -ne 0 ]] && __rm=""
+    [[ ${persist} -ne 0 ]] && __rm=""
 
     docker run -it ${__rm} \
         --privileged \
@@ -142,16 +152,16 @@ function run_container () {
         -p 8888:8888                        \
         -p 8889:8889                        \
         \
-        doorbellian:dev ${container_cmd} ${container_args}
+        doorbellian:${image_tag} ${container_cmd} ${container_args}
 }
 
 # (1: container command; 2: container command arguments)
 function exec_container () {
     local container_cmd=$1
     local container_args=$2
-    local container_id="$(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}')"
+    local container_id="$(docker ps -a --filter \"ancestor=doorbellian:${image_tag}\" --format '{{.ID}}')"
 
-    [[ ! $container_id ]] && caller && echo "[ERROR]: Could not find an existing container..." && exit 10
+    [[ ! ${container_id} ]] && caller && echo "[ERROR]: Could not find an existing container..." && exit 10
 
     docker start ${container_id} >/dev/null
     docker exec -it ${container_id} ${container_cmd} ${container_args}
@@ -160,32 +170,32 @@ function exec_container () {
 # ================================================================================================
 #                                              FLAGS
 add_flag "d" "debug" "enable debug mode (prints extra info)" 0
-function flag_d () {
+function flag_name_debug () {
     debug_mode=1
     debug "Enabling Debug Mode"
 }
 
 add_flag "f" "force" "run even if no camera devices are found" 1
-function flag_f () {
-    echo forcing...
-    force=y
+function flag_name_force () {
+    debug "forcing..."
+    force=1
 }
 
 add_flag "p" "persistent" "container should persist after use" 1
-function flag_p () {
+function flag_name_persistent () {
     persist=1
-    echo "Container will persist after use."
+    debug "Container will persist after use."
 }
 
 add_flag "a" "attach" "attach to existing persistent container if one exists" 2
-function flag_a () {
+function flag_name_attach () {
     attach=1
     if [[ -z "${container_id}" ]]; then
-        local container_ids=($(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null))
+        local container_ids=($(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null))
         if [[ ${#container_ids} -eq 0 ]]; then
             created_container=1
-            echo "Creating container..."
-            container_id="$(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null)"
+            debug "Creating container..."
+            container_id="$(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null)"
         elif [[ ${#container_ids} -eq 1 ]]; then
             container_id="$container_ids"
         else
@@ -193,11 +203,11 @@ function flag_a () {
             container_id="${container_ids[selected_item_index]}"
         fi
     fi
-    echo "Attaching to container [${container_id:0:8}]..."
+    debug "Attaching to container [${container_id:0:8}]..."
 }
 
 # add_flag "u" "update" "updates a container by copying the contents of 'deps/' into a currently running container before executing the target ; implicitly uses the -a flag" 2
-function flag_u () {
+function flag_name_update () {
     flag_a
     local container_ids=
     return
@@ -208,24 +218,51 @@ function flag_name_auto () {
     auto_select=1
 }
 
-add_flag "-" "jobs" "sets the number of jobs/threads to use" 1
-function flag_name_jobs () {
-    JOBS=${arguments[0]}
-    [[ ! ${JOBS} =~ ^[0-9]+$ ]] && caller && echo "[ERROR]: JOBS value '${JOBS}' is not a valid number!" && exit 15
+add_flag "-" "tag" "sets the docker tag for the selected target" 2
+function flag_name_tag () {
+    image_tag="${arguments[0]}"
+    debug "using tag '${image_tag}'"
     arr_pop arguments 0
 }
 
-add_flag "-" "dockerfile" "sets the dockerfile to use" 1 "dockerfile" "the dockerfile to use"
+add_flag "-" "jobs" "sets the number of jobs/threads to use" 1
+function flag_name_jobs () {
+    [[ ! ${JOBS} =~ ^[0-9]+$ ]] && caller && echo "[ERROR]: JOBS value '${JOBS}' is not a valid number!" && exit 15
+    JOBS=${arguments[0]}
+    arr_pop arguments 0
+    debug "Using -j${JOBS}"
+}
+
+add_flag "-" "dockerfile" "sets the dockerfile to use" 2 "dockerfile" "the dockerfile to use"
 function flag_name_dockerfile () {
     dockerfile="${arguments[0]}"
     arr_pop arguments 0
-    echo "using dockerfile '${dockerfile}'"
+    debug "using dockerfile '${dockerfile}'"
 }
 
 add_flag "-" "container" "the id for the container that should be used" 1 "container_id" "the id of the docker container that should be used"
 function flag_name_container () {
     container_id="${arguments[0]}"
-    return
+    debug "Using container [${container_id}]"
+}
+
+add_flag "-" "tina" "a shorthand flag for tina-based doorbellian development ; default is linux6.4 + busybox" 1
+function flag_name_tina () {
+    dockerfile="Dockerfile.tina"
+    image_tag="tina"
+    debug "using dockerfile '${dockerfile}'"
+    debug "using tag '${image_tag}'"
+}
+
+add_flag "-" "args" "additional arguments to pass to the target ; can be used multiple times" 1
+function flag_name_args () {
+    local args=("${arguments[0]}" "test")
+    echo "${args[0]};${args[1]}"
+    IFS="," echo "args: <${args[@]}>"
+    extra_args+=(${args})
+    arr_pop arguments 0
+    # IFS=',' echo "args: <${extra_args[@]}>"
+    # exit 0
 }
 
 # ================================================================================================
@@ -235,9 +272,9 @@ function target_usb () {
     usb_init
 
     echo ==============================================================
-    echo -e "$cam_output"
+    echo -e "${cam_output}"
     echo ==============================================================
-    echo -e "$lsusb_output"
+    echo -e "${lsusb_output}"
     echo ==============================================================
 
     # Print the extracted IDs
@@ -247,49 +284,54 @@ function target_usb () {
     echo "Extracted USB List:      ${usb_list[@]}"
 
     echo ==============================================================
+
+    validate_usb_devices
+    [[ ${force} -eq 0 ]] && echo "found USB devices are all valid!"
 }
 
 add_target "clean" "clean out the related containers and images, and dangling images"
 function target_clean () {
-    echo cleaning...
+    debug "cleaning..."
     docker ps -a --filter "status=created" --format "{{.ID}}" | xargs -r docker rm
     docker ps -a --filter "status=exited" --format "{{.ID}}" | xargs -r docker rm
-    if [[ -n "$(docker images -q doorbellian:dev 2> /dev/null)" ]]; then
-        docker image rm --force doorbellian:dev
+    if [[ -n "$(docker images -q doorbellian:${image_tag} 2> /dev/null)" ]]; then
+        [[ ! -z "${image_tag}" ]] && docker image rm --force doorbellian:${image_tag} || docker image rm --force doorbellian
     fi
     docker images -f "dangling=true" --format "{{.ID}}" | xargs -r docker rmi
-    echo cleaned.
+    debug "cleaned."
 }
 
 add_target "build" "build the docker image"
 function target_build () {
     export DOCKER_BUILDKIT=0
-    # --rm=false
     docker build --build-arg JOBS=${JOBS} --progress=plain -f "${dockerfile}" \
-        -t doorbellian:dev .
+        -t doorbellian:${image_tag} .
     return $?
 }
 
 add_target "extract" "extract logs from the constructed image"
 function target_extract () {
-    if [[ -n "$(docker images -q doorbellian:dev 2> /dev/null)" ]]; then
+    if [[ -n "$(docker images -q doorbellian:${image_tag} 2> /dev/null)" ]]; then
         local extracts=(${arguments[@]})
-        local container_id=($(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null))
+        local container_ids=($(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null))
+        local container_id=""
         local created=0
 
-        [[ ${#container_id[@]} -gt 1 ]] && IFS=',' echo "[ERROR]: too many available containers: (${container_id[*]})" && exit 20
-        [[ ${#container_id[@]} -eq 0 ]] && created=1 && container_id=($(docker create doorbellian:dev))
+        [[ ${#container_ids[@]} -gt 1 ]] && IFS=',' echo "[ERROR]: too many available containers: (${container_id[*]})" && exit 20
+        [[ ${#container_ids[@]} -eq 0 ]] && created=1 && container_id="$(docker create doorbellian:${image_tag})" || container_id=${container_ids[0]}
 
         for extracted in "${extracts[@]}"; do
             IFS=';' read -ra extracted_parts <<< "${extracted}"
             local _from="${extracted_parts[0]}"
             local _to="${extracted_parts[0]}"
-            IFS='#' echo "(${extracted_parts[@]})"
+            # IFS='#' echo "(${extracted_parts[@]})"
             [[ ${#extracted_parts} -gt 1 ]] && _to="${extracted_parts[1]}"
-            echo "Extracted '${container_id:0:8}:${_from}' to 'tmp/${_to}'"
+            echo "Extracted ${container_id:0:8}:'${_from}' to 'tmp/${_to}'"
             docker cp "${container_id}:${_from}" "tmp/${_to}" 2>&1 >/dev/null
         done
         [[ ${created} -eq 1 ]] && docker rm -v ${container_id} 2>&1 >/dev/null
+    else
+        echo "No valid images found to extract from! Please run '${SCRIPT_NAME} --tag ${image_tag} --dockerfile ${dockerfile} build'"
     fi
 }
 
@@ -302,8 +344,9 @@ function target_bae () {
 add_target "run" "run docker container with default command"
 function target_run () {
     usb_init
+    validate_usb_devices
     local _target="run_container"
-    local container_ids=($(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null))
+    local container_ids=($(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null))
     [[ ${attach} -ne 0 && ${#container_ids} -eq 1 ]] && _target="exec_container"
     eval "${_target} \"./doorbellian-qemu.sh\" ${usb_list[@]}"
 }
@@ -311,14 +354,14 @@ function target_run () {
 add_target "bash" "run docker container with /bin/bash"
 function target_bash () {
     local _target="run_container"
-    local container_ids=($(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null))
+    local container_ids=($(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null))
     [[ ${attach} -ne 0 && ${#container_ids} -eq 1 ]] && _target="exec_container"
     eval "${_target} '/bin/bash'"
 }
 
 add_target "kill" "kills and deletes related running containers"
 function target_kill () {
-    local container_ids=($(docker ps -a --filter 'ancestor=doorbellian:dev' --format '{{.ID}}' 2>/dev/null))
+    local container_ids=($(docker ps -a --filter "ancestor=doorbellian:${image_tag}" --format '{{.ID}}' 2>/dev/null))
     [[ ${#container_ids[@]} -eq 0 ]] && echo "No containers to kill." && return
 
     for container_id in "${container_ids[@]}"; do
@@ -332,9 +375,7 @@ function target_kill () {
 
 add_target "bar" "build target followed by run target"
 function target_bar () {
-    target_build
-    built=$?
-    [[ $built -eq 0 ]] && target_run && return
+    target_build && target_run && return
     echo "[Error]: Build failed, exiting..."
     exit 100
 }
